image: registry.git.rwth-aachen.de/ths/smt/smtrat:latest

#Gleicher Cache für alle Branches, Verschiedene für jeden Job
cache: &global_cache
  key: ${CI_JOB_NAME}
  paths:
    - build/resources/
  policy: pull-push

stages:
  - build
  - test #Todo

#update dependencies if necessary
#resources: 
#  stage: dependencies
#  script:
#     - MAKE_PARALLEL=-j12 TASK=dependencies COMPILER=g++-10 source .ci/build.sh
#  cache:
#    <<: *global_cache #override global cache settings to allow pushing
#    policy: pull-push
#  only:
#    - ci-kroll

build-gcc10:
  stage: build
  script:
     - MAKE_PARALLEL=-j12 TASK=parallel COMPILER=g++-10 source .ci/build.sh
  only:
    - ci-kroll

build-gcc9:
  stage: build
  script:
     - MAKE_PARALLEL=-j12 TASK=parallel COMPILER=g++-9 source .ci/build.sh
  only:
    - ci-kroll