image: registry.git.rwth-aachen.de/ths/smt/smtrat/ci:latest

#Verschiedene für jeden Job und Branches -> Erste Pipeline in einem neuen Branch wird lange dauern
#Für alle Jobs der gleiche Cache klappt leider nicht, da diese bei verschiedenen Compilern neu compiliert werden müssen
cache: 
  key: ${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}
  paths:
    - build/resources/
  policy: pull-push


stages:
  - build-gcc
  - build-clang #Carl Singleton redefinition Todo
  - test #Todo



build-gcc10:
  stage: build-gcc
  script:
     - export CC=/usr/bin/gcc-10 && export CXX=/usr/bin/g++-10
     - TASK=getCarl BRANCH_NAME=${CI_COMMIT_BRANCH} JOB_NAME=${CI_JOB_NAME} TOKEN=${CARL_READONLY_TOKEN} source .ci/build.sh
     - TASK=parallel MAKE_PARALLEL=-j12 source .ci/build.sh
  only:
    - ci-kroll

build-gcc9:
  stage: build-gcc
  script:
     - export CC=/usr/bin/gcc-9 && export CXX=/usr/bin/g++-9
     - TASK=getCarl BRANCH_NAME=${CI_COMMIT_BRANCH} JOB_NAME=${CI_JOB_NAME} TOKEN=${CARL_READONLY_TOKEN} source .ci/build.sh
     - TASK=parallel MAKE_PARALLEL=-j12 source .ci/build.sh
  only:
    - ci-kroll
  
build-gcc8:
  stage: build-gcc
  script:
     - export CC=/usr/bin/gcc-8 && export CXX=/usr/bin/g++-8
     - TASK=getCarl BRANCH_NAME=${CI_COMMIT_BRANCH} JOB_NAME=${CI_JOB_NAME} TOKEN=${CARL_READONLY_TOKEN} source .ci/build.sh
     - TASK=parallel MAKE_PARALLEL=-j12  source .ci/build.sh
  only:
    - ci-kroll

build-clang11:
  stage: build-clang
  script:
     - export CC=/usr/bin/clang-11 && export CXX=/usr/bin/clang++-11
     - TASK=getCarl BRANCH_NAME=${CI_COMMIT_BRANCH} JOB_NAME=${CI_JOB_NAME} TOKEN=${CARL_READONLY_TOKEN} source .ci/build.sh
     - TASK=parallel MAKE_PARALLEL=-j12  source .ci/build.sh
  only:
    - ci-kroll

build-clang10:
  stage: build-clang
  script:
     - export CC=/usr/bin/clang-10 && export CXX=/usr/bin/clang++-10
     - TASK=getCarl BRANCH_NAME=${CI_COMMIT_BRANCH} JOB_NAME=${CI_JOB_NAME} TOKEN=${CARL_READONLY_TOKEN} source .ci/build.sh
     - TASK=parallel MAKE_PARALLEL=-j12  source .ci/build.sh
  only:
    - ci-kroll

build-clang9:
  stage: build-clang
  script:
     - export CC=/usr/bin/clang-9 && export CXX=/usr/bin/clang++-9
     - TASK=getCarl BRANCH_NAME=${CI_COMMIT_BRANCH} JOB_NAME=${CI_JOB_NAME} TOKEN=${CARL_READONLY_TOKEN} source .ci/build.sh
     - TASK=parallel MAKE_PARALLEL=-j12 source .ci/build.sh
  only:
    - ci-kroll