cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - build/resources

.setup:
  before_script: &setup-before_script
    - apt update 
    - apt -y install make texinfo time uuid-dev cmake flex bison
    - git config --global user.email "runner@ths.rwth-aachen.de"

dependencies-gcc-9:
  extends: .setup
  image: gcc:9
  cache: {}
  script:
    - MAKE_PARALLEL=-j4 TASK=dependencies source .ci/build.sh
  only:
    - development

docs-gcc-9:
  extends: .setup
  image: gcc:9
  before_script:
    - *setup-before_script
    - apt -y install ghostscript graphviz libclang-7-dev lmodern texinfo texlive texlive-font-utils texlive-latex-extra texlive-plain-generic python3-pip python3-setuptools
  script:
    - MAKE_PARALLEL=-j4 TASK=documentation source .ci/build.sh
  only:
    - master

tidy-clang-9:
  extends: .setup
  image: silkeh/clang:9
  script:
    - MAKE_PARALLEL=-j4 TASK=tidy source .ci/build.sh
  except:
    - master

.build:
  extends: .setup
  before_script:
    - *setup-before_script
    - apt -y libboost-all-dev
  script:
    - MAKE_PARALLEL=-j4 TASK=parallel source .ci/build.sh

.build-clang:
  extends: .setup
  before_script:
    - *setup-before_script
    - apt -y libboost-all-dev
    - apt -y install python3
  script:
    - CC=clang CXX=clang++ MAKE_PARALLEL=-j4 TASK=parallel source .ci/build.sh

build-gcc-8:
  extends: .build
  image: gcc:8
  only:
    - development

build-gcc-9:
  extends: .build
  image: gcc:9
  except:
    - master

build-gcc-10:
  extends: .build
  image: gcc:10
  only:
    - development

build-clang-5:
  extends: .build-clang
  image: silkeh/clang:5
  only:
    - development

build-clang-9:
  extends: .build-clang
  image: silkeh/clang:9
  except:
    - master

build-clang-11:
  extends: .build-clang
  image: silkeh/clang:11
  only:
    - development
