# see https://hub.docker.com/_/gcc/

# TODO development only

build-gcc-8:
  image: gcc:8
  # stage: build
  before_script:
    - apt update && apt -y install make texinfo time uuid-dev cmake flex bison
  script:
    - MAKE_PARALLEL=-j1 TASK=parallel source .ci/build.sh