image: registry.git.rwth-aachen.de/ths/smt/smtrat:latest

#Gleicher Cache f端r alle Branches, Verschiedene f端r jeden Job
#F端r alle Jobs der gleiche Cache klappt leider nicht, da diese bei verschiedenen Compilern neu compiliert werden m端ssen
cache: &global_cache
  key: ${CI_JOB_NAME}
  paths:
    - build/resources/
  policy: pull-push

stages:
  - build-gcc
  - build-clang
  - test #Todo

#update dependencies if necessary
#resources: 
#  stage: dependencies
#  script:
#     - MAKE_PARALLEL=-j12 TASK=dependencies COMPILER=g++-10 source .ci/build.sh
#  cache:
#    <<: *global_cache #override global cache settings to allow pushing
#    policy: pull-push
#  only:
#    - ci-kroll

build-gcc10:
  stage: build-gcc
  script:
     - MAKE_PARALLEL=-j12 TASK=parallel COMPILER=g++-10 source .ci/build.sh
  only:
    - ci-kroll

build-gcc9:
  stage: build-gcc
  script:
     - MAKE_PARALLEL=-j12 TASK=parallel COMPILER=g++-9 source .ci/build.sh
  only:
    - ci-kroll
  
build-gcc8:
  stage: build-gcc
  script:
     - MAKE_PARALLEL=-j12 TASK=parallel COMPILER=g++-8 source .ci/build.sh
  only:
    - ci-kroll

build-clang11:
  stage: build-clang
  script:
     - export CC=/usr/bin/clang-11 && export CXX=/usr/bin/clang++-11
     - MAKE_PARALLEL=-j12 TASK=parallel COMPILER=clang++-11 source .ci/build.sh
  only:
    - ci-kroll

build-clang10:
  stage: build-clang
  script:
     - export CC=/usr/bin/clang-10 && export CXX=/usr/bin/clang++-10
     - MAKE_PARALLEL=-j12 TASK=parallel COMPILER=clang++-10 source .ci/build.sh
  only:
    - ci-kroll

build-clang9:
  stage: build-clang
  script:
     - export CC=/usr/bin/clang-9 && export CXX=/usr/bin/clang++-9
     - MAKE_PARALLEL=-j12 TASK=parallel COMPILER=clang++-9 source .ci/build.sh
  only:
    - ci-kroll