language: cpp

sudo: required

os:
  - linux
  - osx

env:
  - USE=g++-4.8
  - USE=g++-4.9
  - USE=clang++-3.4
  - USE=clang++-3.5
  - USE=clang++-3.5 TASK=doxygen

matrix:
  exclude:
    - os: osx
      env: USE=g++-4.8
    - os: osx
      env: USE=g++-4.9
    - os: osx
      env: USE=clang++-3.4
    - os: osx
      env: USE=doxygen TASK=doxygen

before_install:
  - cd .travis/ && source setup_travis.sh && cd ../

script:
  - source .travis/build.sh

notifications:
  email:
    on_failure: always
    on_success: change
