language: generic
sudo: required
dist: trusty

cache:
  apt: true

_apt_packages:
  sources_boost: &sources_boost
    - boost-latest
  packages_boost: &packages_boost
    - libboost1.55-all-dev
  sources_cmake: &sources_cmake
    - george-edison55-precise-backports
  packages_cmake: &packages_cmake
    - cmake
    - cmake-data

addons:
  apt:
    sources: &sources_base
      - *sources_boost
      - *sources_cmake
      - ubuntu-toolchain-r-test
    packages: &packages_base
      - *packages_boost
      - *packages_cmake
      - g++-6
      - libcln-dev
      - libeigen3-dev
      - libgmp-dev
      - libgtest-dev
      - openjdk-7-jdk
      - time

matrix:
  include:
    - os: linux
      env: USE=clang++-3.6
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.6]
          packages: [*packages_base, clang-3.6]
    - os: linux
      env: USE=clang++-3.7
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.7]
          packages: [*packages_base, clang-3.7]
    - os: linux
      env: USE=clang++-3.8
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.8]
          packages: [*packages_base, clang-3.8]
    - os: linux
      env: USE=clang++-3.9
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-3.9]
          packages: [*packages_base, clang-3.9]
    - os: linux
      env: USE=clang++-4.0
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-4.0]
          packages: [*packages_base, clang-4.0]
    - os: linux
      env: USE=g++-5
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, g++-5]
    - os: linux
      env: USE=g++-6
    - os: osx
      osx_image: xcode7.3
      env: USE=clang++-7.4
    - os: osx
      osx_image: xcode8.2
      env: USE=clang++-8.0
    - os: osx
      osx_image: xcode8.3
      env: USE=clang++-8.1
    - os: linux
      env: USE=g++-6 TASK=doxygen
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, doxygen, texinfo, texlive]

before_install:
  - cd .travis/ && source setup_travis.sh && cd ../

script:
  - source .travis/build.sh
  
notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#carl"
    template:
      - "Commit to %{repository_name}/%{branch} from %{author}"
      - "%{commit_message}"
      - "Build: %{message} %{duration} %{build_url}"
